# Generated by Django 3.1.8 on 2022-02-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_composition', '0002_ingredienthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredienthistory',
            options={},
        ),
    ]
